### ISSUE TITLE
randomint64函数存在随机出0的可能性

### ISSUE THREAD

**Issue by idada** [cloudwu/stable-connection#2]
云风你好，我发现randomint64存在随机出0的可能性，虽然概率极低。

如果0值被用于生成DH交换的公钥，会进一步引发程序崩溃。

我看了DH算法介绍，有要求私钥是大于等于1的随机数。

**Comment by cloudwu** [comment]
其实 powmodp 的两个参数都不能为 0 (均可能导致后续计算栈溢出)
所以不光是 random 这里要确保不为 0, 还应该防止有人发送恶意的 0 握手包.

**Comment by bg5sbk** [comment]
:+1:
